name: Run CI
run-name: ${{ github.actor }} is running module tests triggered by ${{github.event_name }} event.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
jobs:
  LEC-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack
      - name: Build Test
        run: stack build
      - name: Unit Test
        run: stack test
